# Generated by Django 4.1.5 on 2023-08-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0003_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
